### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by franfranfranfran** [Jahmad730/TeaCozy#3]
nice start using indentation to keep everything neat and readable. try to keep it as consistent as possible throughout both the html and css. everything that is nested to the same level should be indented the same to indicate that relationship. if something is nested inside something else, it should be indented one level further. take a look at sections like the [store](https://github.com/Jahmad730/TeaCozy/blob/master/index.html#L44-L64) section to see what i mean.

**Comment by Jahmad730** [comment]
Corrected updating
